### ISSUE TITLE
Erreur 522 format json invalide

### ISSUE THREAD

**Issue by LouisSimon2020** [EduWireApps/ecoledirecte-api-docs#18]
Bonjour, en faisant ma requête post api login j'ai l'erreur 522 et je ne sais pas quoi faire pourriez-vous m'aider ?
Merci d'avance
![image](https://github.com/EduWireApps/ecoledirecte-api-docs/assets/61110029/67095f55-71cf-4feb-bd7a-c3b0b9b404b3)

**Comment by MrBeam89** [comment]
Bonsoir, pouvez-vous me montrer le contenu de votre requête ?

**Comment by roumano** [comment]
Pareil et je tente de faire ca :
```
> POST https://api.ecoledirecte.com/v3/login.awp
> useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
> content-type: application/json
> data {"identifiant":"xxx","motdepasse":"yyyy","isRelogin":false,"uuid":""}

{
  "code": 522,
  "token": "",
  "message": "Format JSON invalide.\nPour la chaîne du JEDObject",
  "data": {
    "changementMDP": false,
    "accounts": []
  }
}
```

**Comment by LouisSimon2020** [comment]
Bonjour Roumano,Pour résoudre le problème il faut que tu rajoutes data= devant ta requête :ton body: data={ « identifiant » : « xxxx »,              « motdepasse »: « xxxxx »,Ext…. }Cordialement,L-SimonEnvoyé de mon iPadLe 23 janv. 2024 à 12:55 PM, roumano ***@***.***> a écrit :﻿
Pareil et je tente de faire ca :
> POST https://api.ecoledirecte.com/v3/login.awp
> useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
> content-type: application/json
> data {"identifiant":"xxx","motdepasse":"yyyy","isRelogin":false,"uuid":""}

{
  "code": 522,
  "token": "",
  "message": "Format JSON invalide.\nPour la chaîne du JEDObject",
  "data": {
    "changementMDP": false,
    "accounts": []
  }
}

**Comment by roumano** [comment]
Salut,

Pour tester, j'utilise un soft qui s'appelle Bruno, meme avec 
```
data={
"identifiant": "XXXx",
"motdepasse": "YYYY",
"isRelogin": false,
"uuid": ""
}
``` 
j'ai l'erreur 522, il y a peut etre un truc que j'ai pas compris , ...

Mais le but finale est de pouvoir mettre ça dans Home Assistant (via multiscrape) et si j'écrit ça : 
```
# Ecole Direct
- name: ecole_direct
  resource: https://api.ecoledirecte.com/v3/login.awp
  scan_interval: 0
  method: POST
  headers:
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Content-Type: application/json
    User-Agent: Wget/1.20.3 (linux-gnu)
  payload: 'data={"identifiant": "yyyyy", "motdepasse": "xxxx", "isRelogin": false, "uuid": ""}'
  button:
    - name: Ecole Direct Force refresh Information
      unique_id: ecole_direct
  sensor:
    - name: Ecole Direct
      value_template: "{{ value_json }}"
```
J'ai le même comportement :   
```
janv. 24 23:31:13 pi hass[32820]: 2024-01-24 23:31:13.811 DEBUG (MainThread) [custom_components.multiscrape.sensor] ecole_direct # Ecole Direct # Selected: {'code': 522, 'token': '', 'message': 'Format JSON invalide.\nPour la chaîne du JEDObject', 'data': {'changementMDP': False, 'accounts': []}}
```
