### ISSUE TITLE
Cahier de text

### ISSUE THREAD

**Issue by roumano** [EduWireApps/ecoledirecte-api-docs#24]
Bonjour,

J'arrive pas a utiliser l'api pour récuperer le cahier de texte (ou le cahier de texte du jour)

Voici mon code utiliser : 
```
- name: ecole_direct_cahier
  resource: https://api.ecoledirecte.com/v3/Eleves/XXXX/cahierdetexte.awp
  scan_interval: 0
  method: GET
  headers:
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Content-Type: application/x-www-form-urlencoded
    User-Agent: Wget/1.20.3 (linux-gnu)
    X-Token: 'YYYYYY'
  button:
    - name: Ecole Direct Force refresh Cahier
      unique_id: ecole_direct_cahier
  sensor:
    - name: Ecole Direct Cahier
      value_template: "{{ value_json }}"
```
où j'ai mis : 
YYYY : reponse_de_login.awp.token
XXXX : reponse_de_login.awp.data.accounts[0].id  ( compte enfant, donc un seul compte dans la réponse )

j'ai ce message : 
```
{'code': 225, 'token': '', 'host': 'HTTP132', 'message': 'Paramètres spécifiés incorrects !'}
```

Idem pour l'url `cahierdetexte/2024-01-02.awp`
